/-
Copyright (c) 2026 vvauted. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: vvauted
-/
import Ram.LocalCompiler
import Ram.SafeSource
import Ram.LocalCall

/-!
# Exact source counts for callee-sized frames

`LocalMeasuredExec` retains the computations and safety premises of `SafeExec`.
Its counts come from the instruction blocks generated by `LocalCompiler` and
the concrete callee-sized ABI. A function's declared local bound determines its
call overhead; the reserved-register boundary does not price the call.

The closed simulation below proves that these counts are actual machine
transitions. Recursive bodies use the induction hypothesis at their own local
bound; no unproved call-simulation assumption remains.
-/

namespace Ram.Source

/-- Safe execution with exact counts from the local-frame compiler. `control`
locates reserved registers; `depth` separately bounds nested source calls. -/
inductive LocalMeasuredExec (control : Nat) (program : Program) (heapLimit : Nat)
    {w : Nat} : Nat → Stmt → Nat → State w → State w → Prop where
  | skip : LocalMeasuredExec control program heapLimit d .skip 0 s s
  | assign (reads : value.ReadsBelow heapLimit s.regs s.mem) :
      LocalMeasuredExec control program heapLimit d (.assign dst value)
        (LocalCompiler.stmtSize control (LocalCompiler.calleeLocals program)
          (.assign dst value)) s (s.setReg dst (s.eval value))
  | store (addressReads : address.ReadsBelow heapLimit s.regs s.mem)
      (valueReads : value.ReadsBelow heapLimit s.regs s.mem)
      (destination : (s.eval address).toNat < heapLimit) :
      LocalMeasuredExec control program heapLimit d (.store address value)
        (LocalCompiler.stmtSize control (LocalCompiler.calleeLocals program)
          (.store address value)) s (s.setMem (s.eval address) (s.eval value))
  | seq (first : LocalMeasuredExec control program heapLimit d a na s middle)
      (second : LocalMeasuredExec control program heapLimit d b nb middle t) :
      LocalMeasuredExec control program heapLimit d (.seq a b) (na + nb) s t
  | iteTrue (reads : c.ReadsBelow heapLimit s.regs s.mem)
      (condition : s.eval c ≠ 0)
      (body : LocalMeasuredExec control program heapLimit d yes nb s t) :
      LocalMeasuredExec control program heapLimit d (.ite c yes no)
        ((c.compile (ABI.scratch control)).length + 1 + nb + 1) s t
  | iteFalse (reads : c.ReadsBelow heapLimit s.regs s.mem)
      (condition : s.eval c = 0)
      (body : LocalMeasuredExec control program heapLimit d no nb s t) :
      LocalMeasuredExec control program heapLimit d (.ite c yes no)
        ((c.compile (ABI.scratch control)).length + 1 + nb) s t
  | whileFalse (reads : c.ReadsBelow heapLimit s.regs s.mem)
      (condition : s.eval c = 0) :
      LocalMeasuredExec control program heapLimit d (.while c body)
        ((c.compile (ABI.scratch control)).length + 1) s s
  | whileTrue (reads : c.ReadsBelow heapLimit s.regs s.mem)
      (condition : s.eval c ≠ 0)
      (body : LocalMeasuredExec control program heapLimit d b nb s middle)
      (rest : LocalMeasuredExec control program heapLimit d (.while c b) nr middle t) :
      LocalMeasuredExec control program heapLimit d (.while c b)
        ((c.compile (ABI.scratch control)).length + 1 + nb + 1 + nr) s t
  | read (available : s.input = value :: rest) :
      LocalMeasuredExec control program heapLimit d (.read dst)
        (LocalCompiler.stmtSize control (LocalCompiler.calleeLocals program) (.read dst))
        s { s.setReg dst value with input := rest }
  | write (reads : value.ReadsBelow heapLimit s.regs s.mem) :
      LocalMeasuredExec control program heapLimit d (.write value)
        (LocalCompiler.stmtSize control (LocalCompiler.calleeLocals program) (.write value))
        s { s with outputRev := s.eval value :: s.outputRev }
  | call (lookup : program[fn]? = some f) (arity : args.length = f.params)
      (frame : f.params ≤ f.locals)
      (arguments : ∀ arg ∈ args, arg.ReadsBelow heapLimit s.regs s.mem)
      (body : LocalMeasuredExec control program heapLimit d f.body bodySteps
        (s.enter (args.map s.eval)) callee)
      (result : f.result.ReadsBelow heapLimit callee.regs callee.mem) :
      LocalMeasuredExec control program heapLimit (d + 1) (.call dst fn args)
        ((ABI.callPrefixLocals control f.locals args 0).length + 1 + bodySteps +
          (ABI.returnCodeLocals control f.locals f.result).length + 1)
        s (s.leave callee dst f.result)

namespace LocalMeasuredExec

/-- Dropping the count preserves every source operation and safety premise. -/
theorem erase {control heapLimit depth steps : Nat} {program : Program} {stmt : Stmt}
    {s t : State w} (h : LocalMeasuredExec control program heapLimit depth stmt steps s t) :
    SafeExec program heapLimit depth stmt s t := by
  induction h with
  | skip => exact .skip
  | assign reads => exact .assign reads
  | store addressReads valueReads destination =>
      exact .store addressReads valueReads destination
  | seq _ _ first second => exact .seq first second
  | iteTrue reads condition _ body => exact .iteTrue reads condition body
  | iteFalse reads condition _ body => exact .iteFalse reads condition body
  | whileFalse reads condition => exact .whileFalse reads condition
  | whileTrue reads condition _ _ body rest =>
      exact .whileTrue reads condition body rest
  | read available => exact .read available
  | write reads => exact .write reads
  | call lookup arity frame arguments _ result body =>
      exact .call lookup arity frame arguments body result

/-- Additional allowed call nesting does not alter the executed count. -/
theorem depth_add {control heapLimit depth steps : Nat} {program : Program} {stmt : Stmt}
    {s t : State w} (h : LocalMeasuredExec control program heapLimit depth stmt steps s t)
    (extra : Nat) :
    LocalMeasuredExec control program heapLimit (depth + extra) stmt steps s t := by
  induction h with
  | skip => exact .skip
  | assign reads => exact .assign reads
  | store addressReads valueReads destination =>
      exact .store addressReads valueReads destination
  | seq _ _ first second => exact .seq first second
  | iteTrue reads condition _ body => exact .iteTrue reads condition body
  | iteFalse reads condition _ body => exact .iteFalse reads condition body
  | whileFalse reads condition => exact .whileFalse reads condition
  | whileTrue reads condition _ _ body rest =>
      exact .whileTrue reads condition body rest
  | read available => exact .read available
  | write reads => exact .write reads
  | call lookup arity frame arguments _ result body =>
      simpa only [Nat.add_right_comm _ 1 extra] using
        (LocalMeasuredExec.call lookup arity frame arguments body result)

theorem mono {control heapLimit depth depth' steps : Nat} {program : Program} {stmt : Stmt}
    {s t : State w} (h : LocalMeasuredExec control program heapLimit depth stmt steps s t)
    (hle : depth ≤ depth') :
    LocalMeasuredExec control program heapLimit depth' stmt steps s t := by
  have h' := h.depth_add (depth' - depth)
  simpa only [Nat.add_sub_of_le hle] using h'

/-- Moving the reserved registers does not change a computation's instruction
count. In particular, a larger global register boundary does not enlarge the
frames of functions whose declared local bounds have stayed the same. -/
theorem rebase {control heapLimit depth steps : Nat} {program : Program} {stmt : Stmt}
    {s t : State w} (h : LocalMeasuredExec control program heapLimit depth stmt steps s t)
    (control' : Nat) :
    LocalMeasuredExec control' program heapLimit depth stmt steps s t := by
  have hlength (e : Expr) (dst : Reg) : (e.compile dst).length = (e.compile 0).length :=
    e.compile_length_eq dst 0
  induction h with
  | skip => exact .skip
  | assign reads =>
      simpa only [LocalCompiler.stmtSize, LocalCompiler.compileStmt,
        List.length_append, hlength] using
        (LocalMeasuredExec.assign (control := control') reads)
  | store addressReads valueReads destination =>
      simpa only [LocalCompiler.stmtSize, LocalCompiler.compileStmt,
        List.length_append, hlength] using
        (LocalMeasuredExec.store (control := control') addressReads valueReads destination)
  | seq _ _ first second => exact .seq first second
  | iteTrue reads condition _ body =>
      simpa only [hlength] using
        (LocalMeasuredExec.iteTrue reads condition body)
  | iteFalse reads condition _ body =>
      simpa only [hlength] using
        (LocalMeasuredExec.iteFalse reads condition body)
  | whileFalse reads condition =>
      simpa only [hlength] using
        (LocalMeasuredExec.whileFalse (control := control') reads condition)
  | whileTrue reads condition _ _ body rest =>
      simpa only [hlength] using
        (LocalMeasuredExec.whileTrue reads condition body rest)
  | read available => exact .read available
  | write reads =>
      simpa only [LocalCompiler.stmtSize, LocalCompiler.compileStmt,
        List.length_append, hlength] using
        (LocalMeasuredExec.write (control := control') reads)
  | call lookup arity frame arguments _ result body =>
      simpa only [ABI.callPrefixLocals_length_eq, ABI.returnCodeLocals_length, hlength] using
        (LocalMeasuredExec.call lookup arity frame arguments body result)

end LocalMeasuredExec

/-- Every safe computation has a local-compiler-derived count, independently
of whether the supplied register boundary is sufficient for its compilation.
Compiler simulation separately requires well-formedness at that boundary. -/
theorem SafeExec.exists_localMeasured {program : Program} {heapLimit depth : Nat}
    {stmt : Stmt} {s t : State w}
    (h : SafeExec program heapLimit depth stmt s t) (control : Nat) :
    ∃ steps, LocalMeasuredExec control program heapLimit depth stmt steps s t := by
  induction h with
  | skip => exact ⟨_, .skip⟩
  | assign reads => exact ⟨_, .assign reads⟩
  | store addressReads valueReads destination =>
      exact ⟨_, .store addressReads valueReads destination⟩
  | seq _ _ first second =>
      obtain ⟨na, ha⟩ := first
      obtain ⟨nb, hb⟩ := second
      exact ⟨_, .seq ha hb⟩
  | iteTrue reads condition _ body =>
      obtain ⟨nb, hb⟩ := body
      exact ⟨_, .iteTrue reads condition hb⟩
  | iteFalse reads condition _ body =>
      obtain ⟨nb, hb⟩ := body
      exact ⟨_, .iteFalse reads condition hb⟩
  | whileFalse reads condition => exact ⟨_, .whileFalse reads condition⟩
  | whileTrue reads condition _ _ body rest =>
      obtain ⟨nb, hb⟩ := body
      obtain ⟨nr, hr⟩ := rest
      exact ⟨_, .whileTrue reads condition hb hr⟩
  | read available => exact ⟨_, .read available⟩
  | write reads => exact ⟨_, .write reads⟩
  | call lookup arity frame arguments _ result body =>
      obtain ⟨nb, hb⟩ := body
      exact ⟨_, .call lookup arity frame arguments hb result⟩

theorem localMeasured_iff_safe {control heapLimit depth : Nat} {program : Program}
    {stmt : Stmt} {s t : State w} :
    (∃ steps, LocalMeasuredExec control program heapLimit depth stmt steps s t) ↔
      SafeExec program heapLimit depth stmt s t :=
  ⟨fun ⟨_, h⟩ => h.erase, fun h => h.exists_localMeasured control⟩

end Ram.Source

namespace Ram.LocalCompiler

/-- Every measured source constructor executes for exactly its declared number
of actual RAM transitions. In the recursive case the body runs at `f.locals`,
which need not equal either the caller's local bound or `control`. -/
theorem simulate_measured {control locals heapLimit depth steps : Nat} {program : Program}
    {main stmt : Stmt} {s s' : Source.State w} (hvalid : Valid control program main)
    (hcodefit : (rawLink control program main).length < 2 ^ w)
    (hx : Source.LocalMeasuredExec control program heapLimit depth stmt steps s s')
    (hwf : stmt.WellFormed locals) :
    SimulationExact control locals heapLimit (rawLink control program main)
      (calleeLocals program) (entry control program main) depth stmt steps s s' := by
  induction hx generalizing locals with
  | skip => exact simulation_skip_exact
  | assign reads => exact simulation_assign_exact hwf reads
  | store addressReads valueReads destination =>
      exact simulation_store_exact hwf addressReads valueReads destination
  | seq _ _ first second => exact simulation_seq_exact (first hwf.1) (second hwf.2)
  | iteTrue reads condition _ body =>
      exact simulation_iteTrue_exact hwf.1 reads condition (body hwf.2.1)
  | iteFalse reads condition _ body =>
      exact simulation_iteFalse_exact hwf.1 reads condition (body hwf.2.2)
  | whileFalse reads condition => exact simulation_whileFalse_exact hwf.1 reads condition
  | whileTrue reads condition _ _ body rest =>
      exact simulation_whileTrue_exact hwf.1 reads condition (body hwf.2) (rest hwf)
  | read available => exact simulation_read_exact hwf available
  | write reads => exact simulation_write_exact hwf reads
  | call lookup arity frame arguments _ result body =>
      have hf := hvalid.2.2 _ (List.mem_of_getElem? lookup)
      have hcount : _ ≤ _ := frame
      rw [← arity] at hcount
      intro hcaller
      exact simulate_call_exact hcaller hf.2.1 (calleeLocals_lookup lookup)
        hwf.1 hwf.2 arguments hcount hf.1.2.2 result (rawLink_function lookup)
        hcodefit (body hf.1.2.1) hcaller

/-- A safe source execution determines a single exact count uniformly for all
matching target states, rather than a target-dependent count chosen afterward. -/
theorem simulate_safe_measured {control locals heapLimit depth : Nat} {program : Program}
    {main stmt : Stmt} {s s' : Source.State w} (hvalid : Valid control program main)
    (hcodefit : (rawLink control program main).length < 2 ^ w)
    (hx : Source.SafeExec program heapLimit depth stmt s s')
    (hwf : stmt.WellFormed locals) :
    ∃ steps, Source.LocalMeasuredExec control program heapLimit depth stmt steps s s' ∧
      SimulationExact control locals heapLimit (rawLink control program main)
        (calleeLocals program) (entry control program main) depth stmt steps s s' := by
  obtain ⟨steps, hsteps⟩ := hx.exists_localMeasured control
  exact ⟨steps, hsteps, simulate_measured hvalid hcodefit hsteps hwf⟩

end Ram.LocalCompiler
