name = "complexityDocs"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"

[[require]]
name = "complexity"
path = ".."

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.28.0-rc1"
