/-
Copyright (c) 2026 vvauted. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: vvauted
-/
import Ram.ABI
import Ram.Amortized.Compilation
import Ram.Amortized.Potential
import Ram.Amortized.Traversal
import Ram.Amortized.Worklist
import Ram.Arguments
import Ram.Arguments.Memory
import Ram.Array
import Ram.Array.BinaryInsertion
import Ram.Array.Contents
import Ram.Array.Contracts
import Ram.Array.Finset
import Ram.Array.Footprint
import Ram.Array.Frame
import Ram.Array.Indexed
import Ram.Array.Merge.Complexity
import Ram.Array.MergeSort.Recursion
import Ram.Array.MergeSort.StateM
import Ram.Array.MergeSort.Time
import Ram.Array.MergeSort.Total
import Ram.Array.MergeSort.Vector
import Ram.Array.Model
import Ram.Array.Observation
import Ram.Array.Ordering
import Ram.Array.Range
import Ram.Array.Refinement
import Ram.Array.Search
import Ram.Array.Slice
import Ram.Array.Sort.Complexity
import Ram.Array.Traversal
import Ram.Atomic
import Ram.Block
import Ram.Call
import Ram.CallReturn
import Ram.CallSetup
import Ram.CodeLength
import Ram.Compiler
import Ram.Complexity
import Ram.Complexity.Encoding
import Ram.Complexity.Logarithm
import Ram.Complexity.Multivariate
import Ram.Complexity.Recurrence
import Ram.Complexity.Recurrence.AkraBazzi
import Ram.Complexity.Recurrence.Balanced
import Ram.Complexity.Recurrence.Finite
import Ram.Complexity.Recurrence.Growth
import Ram.Complexity.Recurrence.Majorant
import Ram.Complexity.Recurrence.Rounding
import Ram.Complexity.Recurrence.Supercritical
import Ram.Complexity.Reduction
import Ram.Complexity.Reparam
import Ram.Complexity.Sum
import Ram.Complexity.SumBounds
import Ram.Complexity.Traversal
import Ram.Component
import Ram.Component.Asymptotics
import Ram.Component.Memory
import Ram.Component.ResourceBound
import Ram.Contracts
import Ram.Control
import Ram.Effects
import Ram.Exact
import Ram.Execution
import Ram.Execution.Block
import Ram.Execution.Memory
import Ram.Execution.MemoryBounds
import Ram.Execution.Resource
import Ram.Expr
import Ram.ExprCompile
import Ram.ExprCompile.Memory
import Ram.Fast
import Ram.Frame
import Ram.Frame.Lifetime
import Ram.Frame.Memory
import Ram.Frame.Prefix
import Ram.Frame.StackLifetime
import Ram.LocalABI.Lifetime
import Ram.LocalABI.Memory
import Ram.LocalABI.Slots
import Ram.LocalABI.Stack
import Ram.LocalAtomic.Memory
import Ram.LocalExact.Stack
import Ram.LocalMeasured.Memory
import Ram.LocalMeasured.Writes
import Ram.LocalProgram
import Ram.LocalProgram.Memory
import Ram.Loop
import Ram.Loop.Logarithmic
import Ram.Loop.Sum
import Ram.Loop.Traversal
import Ram.Machine
import Ram.Matrix.Copy
import Ram.Matrix.Frame
import Ram.Matrix.Memory
import Ram.Matrix.MergeSort
import Ram.Matrix.StateM
import Ram.Matrix.Update
import Ram.Matrix.Writeback
import Ram.Measured
import Ram.Memory
import Ram.Memory.Contracts
import Ram.Memory.Finmap
import Ram.Memory.Finmap.Contracts
import Ram.Memory.Finmap.Frame
import Ram.Memory.Finmap.Lookup
import Ram.Memory.Finmap.StateM
import Ram.Memory.Frame
import Ram.Memory.Indexed
import Ram.Memory.Indexed.Writeback
import Ram.Memory.StateM
import Ram.Named
import Ram.Named.Declaration
import Ram.Problem
import Ram.Problem.Asymptotics
import Ram.Program
import Ram.Recursion
import Ram.RunProgram
import Ram.Runner
import Ram.SafeSource
import Ram.Source
import Ram.Source.State
import Ram.Structural
import Ram.Syntax
import Ram.Tactic
import Ram.Tactic.Budget
import Ram.Tactic.Contract
import Ram.Tactic.Model
import Ram.Tactic.Total
import Ram.Tactic.Word
import Ram.Verification
import Ram.Verification.Amortized
import Ram.Verification.Call
import Ram.Verification.Composition
import Ram.Verification.Control
import Ram.Verification.Frame
import Ram.Verification.Model
import Ram.Verification.Observation
import Ram.Verification.Refinement
import Ram.Verification.Specification
import Ram.Verification.StateM
import Ram.Verification.StateMCall
import Ram.Verification.StateMComposition
import Ram.Verification.StateMFrame
import Ram.Verification.StateMModel
import Ram.Verification.StateMSubtype
import Ram.Verification.StateMTraversal
import Ram.Verification.TimeComposition
import Ram.Verification.TimeCapacity
import Ram.Verification.TimeRecursion
import Ram.Verification.TotalRecursion
import Ram.Word

/-!
# RAM programming and complexity library

The word-RAM backend entry point. The project-wide public import is `Complexity`.
Import a specific `Ram.*` topic to use a smaller dependency set. Example
programs are separate in `Ram.Examples`; importing `Ram` does not import them.
Mathematical foundations reuse the pinned mathlib.
-/
