/-
Copyright (c) 2026 vvauted. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: vvauted
-/
import Complexity.Computability.Ram.Compiler.Language.Program.Capacity
import Complexity.Computability.Ram.Compiler.Language.Arena.Measured.FunctionExecution
import Mathlib.Analysis.Asymptotics.Lemmas

/-!
# Uniform program time from measured source execution

`TimeO.of_measured` joins an actual returning body execution, an independent
structural bound on that same body, and the registered preloaded launch. The
existing compiler supplies initialization, outer-call, return and halt costs.
No source correctness specification or proposed mathematical answer is needed.

`TimeO.of_measured_auto` combines a supplied resource-width constant with the
fixed code and stack constant. Mathematical input validity is not restricted by
a capacity premise. Body readiness must still prove actual numerical ranges,
allocation capacity and the fixed call depth at every admitted width.
-/

namespace Complexity.Program

open Language Ram.LanguageCompiler

universe u v

variable {α : Type u} {β : Type v} [Input α] [Output β]

/-- The complete invocation envelope generated by the existing compiler from
a source-body bound, including two initialization instructions and final halt. -/
def invocationBound (program : Complexity.Program α β) (bodyBound : Nat) : Nat :=
  Ram.LocalCompiler.Function.callSteps (programControl program.source)
    (lowerFunc program.source program.fn) (bodyBound + 2) + 1

/-- For one fixed source program, full-invocation overhead is independent of
the input and body count. The constant is the actual generated call machinery. -/
theorem invocationBound_eq (program : Complexity.Program α β) (bodyBound : Nat) :
    program.invocationBound bodyBound = bodyBound + program.invocationBound 0 := by
  simp only [invocationBound, Ram.LocalCompiler.Function.callSteps]
  omega

/-- A linear body envelope retains its asymptotic bound after the actual fixed
invocation overhead, using mathlib's ordinary constant and addition rules. -/
theorem isBigO_invocationBound_linear (program : Complexity.Program α β)
    {bound : Nat → Nat}
    (bounded : Asymptotics.IsBigO Filter.atTop (fun n => (bound n : ℝ))
      (fun n : Nat => (n : ℝ))) :
    Asymptotics.IsBigO Filter.atTop (fun n => (program.invocationBound (bound n) : ℝ))
      (fun n : Nat => (n : ℝ)) := by
  have overhead : Asymptotics.IsBigO Filter.atTop
      (fun _ : Nat => (program.invocationBound 0 : ℝ)) (fun n : Nat => (n : ℝ)) :=
    (Asymptotics.isLittleO_const_id_atTop (program.invocationBound 0 : ℝ)).isBigO.natCast_atTop
  have equation : (fun n => (program.invocationBound (bound n) : ℝ)) =
      (fun n => (bound n : ℝ) + (program.invocationBound 0 : ℝ)) := by
    funext n
    rw [invocationBound_eq, Nat.cast_add]
  rw [equation]
  exact bounded.add overhead

variable [RamInput α]

/-- Publish uniform time from actual measured returns and a separate body bound.
Launch capacity is proved for every legal input; it is not added to `valid`.
The arbitrary measured observation may retain results, heaps or exact counts. -/
theorem TimeO.of_measured {program : Complexity.Program α β}
    {valid : α → Prop} {size : α → Nat} {growth bound : Nat → Nat}
    {depth overhead : Nat}
    {P : α → Heap → Value program.signatures[program.fn].result → Nat → Nat → Prop}
    (measured : ∀ x, valid x → ∀ w, width overhead x ≤ w →
      ArenaMeasured program.source w (Ram.LanguageCompiler.ArrayFunction.heapLimit w) depth
        (program.source.body program.fn)
        (fun finish control finalCursor steps =>
          ∃ value, control = .returned value ∧ P x finish.heap value finalCursor steps)
        ⟨program.args x, Input.heap x⟩ (RamInput.cursor x))
    (bounded : ∀ x, valid x → ∀ w, width overhead x ≤ w →
      StmtArenaCostBound program.source w (Ram.LanguageCompiler.ArrayFunction.heapLimit w) depth
        (program.source.body program.fn) ⟨program.args x, Input.heap x⟩ (bound (size x)))
    (capacity : ∀ x, valid x → ∀ w, width overhead x ≤ w →
      FunctionCapacity program.source program.fn w depth
        (Ram.LanguageCompiler.ArrayFunction.heapLimit w))
    (asymptotic : Asymptotics.IsBigO Filter.atTop
      (fun n => (program.invocationBound (bound n) : ℝ)) (fun n => (growth n : ℝ))) :
    program.TimeO valid size growth := by
  refine ⟨overhead, fun n => program.invocationBound (bound n), asymptotic, ?_⟩
  intro x legal w admitted
  obtain ⟨finish, value, finalCursor, steps, execution, ready, cost, _⟩ :=
    ArenaMeasured.exists_returned_iff.mp (measured x legal w admitted)
  obtain ⟨outcome, _, _, _, bodyEq⟩ :=
    cost.execute (program.launch (width_base admitted) (capacity x legal w admitted))
  refine ⟨depth, outcome, ?_⟩
  have bodyBound : outcome.bodySteps ≤ bound (size x) + 2 := by
    rw [bodyEq]
    exact Nat.add_le_add_right (bounded x legal w admitted execution ready cost) 2
  rw [outcome.steps_eq]
  exact Nat.add_le_add_right
    (Ram.LocalCompiler.Function.callSteps_mono _ _ bodyBound) 1

/-- Fixed code and stack capacity are supplied automatically by one larger
uniform width constant. Readiness and body bounds keep their original resource
width requirement, without an input-dependent choice of machine scale. -/
theorem TimeO.of_measured_auto {program : Complexity.Program α β}
    {valid : α → Prop} {size : α → Nat} {growth bound : Nat → Nat}
    {depth overhead : Nat}
    {P : α → Heap → Value program.signatures[program.fn].result → Nat → Nat → Prop}
    (measured : ∀ x, valid x → ∀ w, width overhead x ≤ w →
      ArenaMeasured program.source w (Ram.LanguageCompiler.ArrayFunction.heapLimit w) depth
        (program.source.body program.fn)
        (fun finish control finalCursor steps =>
          ∃ value, control = .returned value ∧ P x finish.heap value finalCursor steps)
        ⟨program.args x, Input.heap x⟩ (RamInput.cursor x))
    (bounded : ∀ x, valid x → ∀ w, width overhead x ≤ w →
      StmtArenaCostBound program.source w (Ram.LanguageCompiler.ArrayFunction.heapLimit w) depth
        (program.source.body program.fn) ⟨program.args x, Input.heap x⟩ (bound (size x)))
    (asymptotic : Asymptotics.IsBigO Filter.atTop
      (fun n => (program.invocationBound (bound n) : ℝ)) (fun n => (growth n : ℝ))) :
    program.TimeO valid size growth := by
  let combined := max overhead (program.capacityOverhead depth)
  have smaller (x : α) : width overhead x ≤ width combined x := by
    change (overhead + 1) * _ ≤ (combined + 1) * _
    exact Nat.mul_le_mul_right _ (Nat.add_le_add_right (Nat.le_max_left _ _) 1)
  apply TimeO.of_measured (overhead := combined)
    (fun x legal w admitted => measured x legal w ((smaller x).trans admitted))
    (fun x legal w admitted => bounded x legal w ((smaller x).trans admitted))
    (fun _ _ _ admitted => program.capacity_of_le depth (Nat.le_max_right _ _) admitted)
    asymptotic

end Complexity.Program
