name = "complexityCslib"
version = "0.1.0"
description = "CSLib integration for Complexity"
license = "Apache-2.0"
defaultTargets = ["RamCslib"]

[[require]]
name = "complexity"
path = "../.."

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "232407ba9e7883e71aa57e046f130f52932fc9c8"

[[lean_lib]]
name = "RamCslib"
