/-
Copyright (c) 2026 vvauted. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: vvauted
-/
import Lean.Meta.Tactic.Simp.RegisterCommand

/-!
# Simplification attributes for generated source bindings

The source frontend and proof tactics share this attribute without importing
the source grammar into tactic implementation modules. Its facts describe
declaration bindings, not algorithmic correctness or executable function bodies.
-/

namespace Ram.DSL

/-- Binding equations generated by `ram_def`: argument fields, declaration
lookup and static parameter/result/frame counts. Function bodies, return
expressions and mathematical specifications are not part of this simp set. -/
register_simp_attr ram_bindings

end Ram.DSL
